package com.example.ui.util

import androidx.compose.runtime.Composable
import androidx.compose.runtime.compositionLocalOf

data class AppStrings(
    val appTitle: String,
    val appSubtitle: String,
    
    // Navigation
    val navInventory: String,
    val navScanner: String,
    val navAlerts: String,
    val navAnalytics: String,
    
    // Categories
    val catAll: String,
    val catCars: String,
    val catBikes: String,
    val catSpareParts: String,
    val category: String,
    val selectCategory: String,
    
    // Inventory Screen
    val searchPlaceholder: String,
    val totalInventoryValue: String,
    val totalValuation: String,
    val totalUnits: String,
    val totalItems: String,
    val totalSkus: String,
    val activeAlerts: String,
    val addItem: String,
    val exportPdf: String,
    val scanCode: String,
    val sortBy: String,
    val sortNameAsc: String,
    val sortNameDesc: String,
    val sortQtyHigh: String,
    val sortQtyLow: String,
    val sortPriceHigh: String,
    val sortPriceLow: String,
    val sortValuation: String,
    val inStock: String,
    val lowStock: String,
    val outOfStock: String,
    val quickStockIn: String,
    val quickStockOut: String,
    val viewDetails: String,
    val editItem: String,
    val deleteItem: String,
    val noItemsFound: String,
    val tryAdjustingFilters: String,
    val sku: String,
    val location: String,
    val unitPrice: String,
    val costPrice: String,
    val sellingPrice: String,
    val stockQuantity: String,
    val threshold: String,
    val hsnCode: String,
    val gstRate: String,
    val fitment: String,
    val subcategory: String,
    val description: String,
    val notes: String,
    
    // Scanner
    val scanTitle: String,
    val scanSubtitle: String,
    val scannerTitle: String,
    val scannerSubtitle: String,
    val modeLookup: String,
    val modeStockIn: String,
    val modeStockOut: String,
    val alignBarcodePrompt: String,
    val enterBarcodeManually: String,
    val manualCodeEntry: String,
    val quickTestBarcodes: String,
    val unregisteredBarcode: String,
    val unregisteredBarcodeDesc: String,
    val registerProduct: String,
    val registerNewItem: String,
    val grantPermission: String,
    val lookupSuccess: String,
    val stockInSuccess: String,
    val stockOutSuccess: String,
    val stockOutWarningLow: String,
    val outOfStockCannotDeduct: String,
    val flashlightOn: String,
    val flashlightOff: String,
    val flipCamera: String,
    val cancel: String,
    val save: String,
    val add: String,
    val search: String,
    val barcodeTag: String,
    val recentScansTitle: String,
    val recentScansSubtitle: String,
    val noRecentScans: String,
    val clearHistory: String,
    val copyBarcode: String,
    val barcodeCopied: String,
    
    // Alerts
    val alertsTitle: String,
    val alertsSubtitle: String,
    val allAlerts: String,
    val criticalZero: String,
    val lowStockFilter: String,
    val reorderRecommended: String,
    val reorderRequired: String,
    val quickRestock: String,
    val stockHealthy: String,
    val stockHealthyDesc: String,
    val noAlertsDesc: String,
    
    // Analytics & Ledger
    val analyticsTitle: String,
    val analyticsSubtitle: String,
    val totalCostValue: String,
    val totalRetailValue: String,
    val projectedProfit: String,
    val profitMargin: String,
    val marginProfit: String,
    val departmentBreakdown: String,
    val recentStockLedger: String,
    val auditHistory: String,
    val noTransactions: String,
    
    // Export PDF Dialog
    val pdfExportTitle: String,
    val pdfExportSubtitle: String,
    val exportPdfTitle: String,
    val exportPdfSubtitle: String,
    val reportScope: String,
    val requiredStockUnits: String,
    val requiredStockValuation: String,
    val thresholdUnits: String,
    val sharePdf: String,
    val printPdf: String,
    val previewPdf: String,
    val generatingPdf: String,
    val pdfGenerating: String,
    
    // Dialogs
    val addNewProduct: String,
    val editProduct: String,
    val productDetails: String,
    val enterName: String,
    val enterSku: String,
    val enterBarcode: String,
    val enterSubcategory: String,
    val enterFitment: String,
    val enterLocation: String,
    val enterQty: String,
    val enterThreshold: String,
    val enterCostPrice: String,
    val enterSellingPrice: String,
    val enterHsn: String,
    val enterNotes: String,
    val stockAuditHistory: String,
    val deleteConfirmTitle: String,
    val deleteConfirmMessage: String,
    val confirmDelete: String,
    val language: String,
    val changeLanguage: String
) {
    companion object {
        private val English = AppStrings(
            appTitle = "AutoStock",
            appSubtitle = "PRO",
            navInventory = "Inventory",
            navScanner = "Scanner",
            navAlerts = "Alerts",
            navAnalytics = "Ledger",
            catAll = "All",
            catCars = "Cars",
            catBikes = "Bikes",
            catSpareParts = "Spare Parts",
            category = "Category",
            selectCategory = "Category",
            searchPlaceholder = "Search by name, SKU, barcode, fitment...",
            totalInventoryValue = "Total Value",
            totalValuation = "Total Stock Valuation",
            totalUnits = "Total Units",
            totalItems = "Total Items",
            totalSkus = "Total SKUs",
            activeAlerts = "Alerts",
            addItem = "Add Item",
            exportPdf = "Export PDF",
            scanCode = "Scan",
            sortBy = "Sort By",
            sortNameAsc = "Name (A to Z)",
            sortNameDesc = "Name (Z to A)",
            sortQtyHigh = "Stock (High to Low)",
            sortQtyLow = "Stock (Low to High)",
            sortPriceHigh = "Price (High to Low)",
            sortPriceLow = "Price (Low to High)",
            sortValuation = "Valuation (High to Low)",
            inStock = "In Stock",
            lowStock = "Low Stock",
            outOfStock = "Out of Stock",
            quickStockIn = "Stock In",
            quickStockOut = "Stock Out",
            viewDetails = "Details",
            editItem = "Edit Item",
            deleteItem = "Delete Item",
            noItemsFound = "No items match your filter",
            tryAdjustingFilters = "Try selecting a different category or clearing your search.",
            sku = "SKU",
            location = "Location",
            unitPrice = "Unit Price",
            costPrice = "Acquisition Cost",
            sellingPrice = "Selling Price (MRP)",
            stockQuantity = "Current Stock",
            threshold = "Min Threshold",
            hsnCode = "HSN Code",
            gstRate = "GST Rate",
            fitment = "Vehicle Fitment",
            subcategory = "Subcategory",
            description = "Description",
            notes = "Notes / Invoice #",
            scanTitle = "Barcode Scanner",
            scanSubtitle = "Point camera at EAN-13, QR or Code-128 barcode",
            scannerTitle = "Barcode Scanner",
            scannerSubtitle = "Instant verification & rapid stock updates",
            modeLookup = "Lookup",
            modeStockIn = "Stock In (+1)",
            modeStockOut = "Stock Out (-1)",
            alignBarcodePrompt = "Center barcode within view box",
            enterBarcodeManually = "Enter Code Manually",
            manualCodeEntry = "Manual Code Entry",
            quickTestBarcodes = "Quick Test Barcodes",
            unregisteredBarcode = "Unregistered Barcode",
            unregisteredBarcodeDesc = "This barcode was not found in your inventory database.",
            registerProduct = "Register Product",
            registerNewItem = "Register New Product",
            grantPermission = "Enable Camera",
            lookupSuccess = "Item verified",
            stockInSuccess = "Restocked successfully",
            stockOutSuccess = "Dispatched successfully",
            stockOutWarningLow = "Stock dropped below safety threshold",
            outOfStockCannotDeduct = "Cannot dispatch: stock is 0",
            flashlightOn = "Torch On",
            flashlightOff = "Torch Off",
            flipCamera = "Switch Camera",
            cancel = "Cancel",
            save = "Save",
            add = "Add",
            search = "Search",
            barcodeTag = "Product Barcode Tag",
            recentScansTitle = "Recent Scans",
            recentScansSubtitle = "Last 10 barcodes scanned for quick reference",
            noRecentScans = "No recent scans recorded yet",
            clearHistory = "Clear History",
            copyBarcode = "Copy Code",
            barcodeCopied = "Barcode copied to clipboard",
            alertsTitle = "Stock Watchdog",
            alertsSubtitle = "Items requiring immediate reorder",
            allAlerts = "All Alerts",
            criticalZero = "Out of Stock",
            lowStockFilter = "Low Stock",
            reorderRecommended = "Reorder Required",
            reorderRequired = "Immediate Reorder Required",
            quickRestock = "Quick Restock",
            stockHealthy = "Stock Levels Healthy",
            stockHealthyDesc = "All items are stocked safely above minimum thresholds.",
            noAlertsDesc = "No low stock or out-of-stock items detected.",
            analyticsTitle = "Stock Movement Ledger",
            analyticsSubtitle = "Valuation, margins & audit trail",
            totalCostValue = "Cost Valuation",
            totalRetailValue = "Retail Valuation",
            projectedProfit = "Projected Profit",
            profitMargin = "Profit Margin",
            marginProfit = "Gross Profit Margin",
            departmentBreakdown = "Department Breakdown",
            recentStockLedger = "Stock Movement Ledger",
            auditHistory = "Stock Audit Trail",
            noTransactions = "No stock transactions recorded yet.",
            pdfExportTitle = "Export Inventory Report",
            pdfExportSubtitle = "Generate formatted printable PDF with GST summary",
            exportPdfTitle = "Export Inventory PDF Report",
            exportPdfSubtitle = "Generate formatted PDF report with pricing & GST",
            reportScope = "Report Scope",
            requiredStockUnits = "Required Stock",
            requiredStockValuation = "Required Stock Value",
            thresholdUnits = "Threshold",
            sharePdf = "Share PDF",
            printPdf = "Print PDF",
            previewPdf = "Preview Report",
            generatingPdf = "Generating formatted PDF report...",
            pdfGenerating = "Generating formatted PDF report...",
            addNewProduct = "Add New Product",
            editProduct = "Edit Product Details",
            productDetails = "Product Details",
            enterName = "Product / Part Name",
            enterSku = "SKU Code",
            enterBarcode = "Barcode / EAN-13",
            enterSubcategory = "Subcategory (e.g. Braking, Tyres)",
            enterFitment = "Compatible Models (e.g. Swift, City)",
            enterLocation = "Rack / Bin Location (e.g. R-01-A)",
            enterQty = "Opening Quantity",
            enterThreshold = "Min Reorder Threshold",
            enterCostPrice = "Cost Price (₹)",
            enterSellingPrice = "Selling Price (₹ MRP)",
            enterHsn = "HSN Code",
            enterNotes = "Challan / Invoice Notes",
            stockAuditHistory = "Transaction Audit History",
            deleteConfirmTitle = "Delete Item?",
            deleteConfirmMessage = "This product and all its transaction history will be permanently deleted.",
            confirmDelete = "Delete Product",
            language = "Language",
            changeLanguage = "Change Language"
        )

        private val Hindi = AppStrings(
            appTitle = "ऑटोस्टॉक",
            appSubtitle = "PRO",
            navInventory = "इन्वेंट्री",
            navScanner = "स्कैनर",
            navAlerts = "अलर्ट",
            navAnalytics = "खाता बही",
            catAll = "सभी",
            catCars = "कारें",
            catBikes = "बाइक",
            catSpareParts = "स्पेयर पार्ट्स",
            category = "श्रेणी",
            selectCategory = "श्रेणी चुनें",
            searchPlaceholder = "नाम, SKU, बारकोड या मॉडल खोजें...",
            totalInventoryValue = "कुल मूल्य",
            totalValuation = "कुल स्टॉक मूल्यांकन",
            totalUnits = "कुल इकाइयाँ",
            totalItems = "कुल वस्तुएं",
            totalSkus = "कुल SKU",
            activeAlerts = "अलर्ट",
            addItem = "नया जोड़ें",
            exportPdf = "PDF रिपोर्ट",
            scanCode = "स्कैन",
            sortBy = "क्रमबद्ध करें",
            sortNameAsc = "नाम (अ से ज्ञ)",
            sortNameDesc = "नाम (ज्ञ से अ)",
            sortQtyHigh = "स्टॉक (ज्यादा से कम)",
            sortQtyLow = "स्टॉक (कम से ज्यादा)",
            sortPriceHigh = "कीमत (ज्यादा से कम)",
            sortPriceLow = "कीमत (कम से ज्यादा)",
            sortValuation = "मूल्यांकन (अधिकतम)",
            inStock = "उपलब्ध",
            lowStock = "कम स्टॉक",
            outOfStock = "खत्म",
            quickStockIn = "आवक दर्ज (+1)",
            quickStockOut = "जावक दर्ज (-1)",
            viewDetails = "विवरण",
            editItem = "संशोधन",
            deleteItem = "हटाएं",
            noItemsFound = "कोई आइटम नहीं मिला",
            tryAdjustingFilters = "कृपया श्रेणी बदलें या खोज शब्द साफ करें।",
            sku = "SKU कोड",
            location = "रैक / स्थान",
            unitPrice = "इकाई मूल्य",
            costPrice = "खरीद लागत",
            sellingPrice = "बिक्री मूल्य (MRP)",
            stockQuantity = "वर्तमान स्टॉक",
            threshold = "न्यूनतम सीमा",
            hsnCode = "HSN कोड",
            gstRate = "GST दर",
            fitment = "गाड़ी कम्पैटिबिलिटी",
            subcategory = "उप-श्रेणी",
            description = "विवरण",
            notes = "टिप्पणी / चालान #",
            scanTitle = "बारकोड स्कैनर",
            scanSubtitle = "EAN-13, QR या बारकोड पर कैमरा फोकस करें",
            scannerTitle = "बारकोड स्कैनर",
            scannerSubtitle = "त्वरित जांच एवं स्टॉक प्रविष्टि",
            modeLookup = "जांच (Lookup)",
            modeStockIn = "आवक (+1 In)",
            modeStockOut = "जावक (-1 Out)",
            alignBarcodePrompt = "बारकोड को बॉक्स के बीच में रखें",
            enterBarcodeManually = "मैन्युअल कोड प्रविष्ट करें",
            manualCodeEntry = "मैन्युअल कोड प्रविष्टि",
            quickTestBarcodes = "त्वरित नमूना बारकोड",
            unregisteredBarcode = "अज्ञात बारकोड",
            unregisteredBarcodeDesc = "यह बारकोड इन्वेंट्री डेटाबेस में नहीं मिला।",
            registerProduct = "नया आइटम जोड़ें",
            registerNewItem = "नया उत्पाद पंजीकृत करें",
            grantPermission = "कैमरा अनुमति दें",
            lookupSuccess = "आइटम मिल गया",
            stockInSuccess = "आवक सफलतापूर्वक दर्ज",
            stockOutSuccess = "जावक सफलतापूर्वक दर्ज",
            stockOutWarningLow = "स्टॉक न्यूनतम सीमा से नीचे चला गया",
            outOfStockCannotDeduct = "स्टॉक खत्म है, जावक संभव नहीं",
            flashlightOn = "टॉर्च चालू",
            flashlightOff = "टॉर्च बंद",
            flipCamera = "कैमरा बदलें",
            cancel = "रद्द करें",
            save = "सुरक्षित करें",
            add = "जोड़ें",
            search = "खोजें",
            barcodeTag = "उत्पाद बारकोड टैग",
            recentScansTitle = "हालिया स्कैन",
            recentScansSubtitle = "त्वरित संदर्भ के लिए अंतिम 10 स्कैन किए गए बारकोड",
            noRecentScans = "अभी कोई हालिया स्कैन दर्ज नहीं है",
            clearHistory = "इतिहास साफ करें",
            copyBarcode = "कोड कॉपी करें",
            barcodeCopied = "बारकोड क्लिपबोर्ड पर कॉपी किया गया",
            alertsTitle = "स्टॉक अलर्ट वॉचडॉग",
            alertsSubtitle = "तत्काल ऑर्डर करने योग्य सामग्री",
            allAlerts = "सभी अलर्ट",
            criticalZero = "स्टॉक खत्म (0)",
            lowStockFilter = "कम स्टॉक",
            reorderRecommended = "पुनः ऑर्डर आवश्यक",
            reorderRequired = "तत्काल पुनः ऑर्डर आवश्यक",
            quickRestock = "त्वरित आवक",
            stockHealthy = "स्टॉक स्थिति सामान्य",
            stockHealthyDesc = "सभी पार्ट्स सुरक्षित स्तर पर उपलब्ध हैं।",
            noAlertsDesc = "कोई भी आइटम कम स्टॉक सीमा में नहीं है।",
            analyticsTitle = "स्टॉक खाता बही एवं विश्लेषण",
            analyticsSubtitle = "मूल्यांकन, मुनाफा एवं ऑडिट रिकॉर्ड",
            totalCostValue = "खरीद मूल्यांकन",
            totalRetailValue = "बिक्री मूल्यांकन",
            projectedProfit = "अनुमानित लाभ",
            profitMargin = "लाभ प्रतिशत",
            marginProfit = "सकल लाभ मार्जिन",
            departmentBreakdown = "विभाग अनुसार विश्लेषण",
            recentStockLedger = "हालिया स्टॉक रजिस्टर",
            auditHistory = "स्टॉक ऑडिट इतिहास",
            noTransactions = "अभी कोई लेन-देन दर्ज नहीं है।",
            pdfExportTitle = "इन्वेंट्री PDF रिपोर्ट",
            pdfExportSubtitle = "GST विवरण के साथ प्रिंट योग्य PDF बनाएं",
            exportPdfTitle = "इन्वेंट्री PDF रिपोर्ट तैयार करें",
            exportPdfSubtitle = "मूल्य व GST गणना के साथ प्रिंट योग्य रिपोर्ट",
            reportScope = "रिपोर्ट दायरा",
            requiredStockUnits = "आवश्यक स्टॉक (थ्रेशहोल्ड हेतु)",
            requiredStockValuation = "आवश्यक स्टॉक मूल्य",
            thresholdUnits = "न्यूनतम सीमा",
            sharePdf = "PDF साझा करें",
            printPdf = "PDF प्रिंट करें",
            previewPdf = "रिपोर्ट देखें",
            generatingPdf = "PDF रिपोर्ट तैयार की जा रही है...",
            pdfGenerating = "PDF रिपोर्ट तैयार की जा रही है...",
            addNewProduct = "नया उत्पाद जोड़ें",
            editProduct = "उत्पाद विवरण बदलें",
            productDetails = "उत्पाद सम्पूर्ण विवरण",
            enterName = "पार्ट्स / मॉडल का नाम",
            enterSku = "SKU कोड",
            enterBarcode = "बारकोड / EAN-13",
            enterSubcategory = "उप-श्रेणी (उदा. ब्रेकिंग, टायर)",
            enterFitment = "गाड़ी मॉडल (उदा. स्विफ्ट, सिटी)",
            enterLocation = "रैक स्थान (उदा. R-01-A)",
            enterQty = "शुरुआती स्टॉक",
            enterThreshold = "न्यूनतम रीऑर्डर सीमा",
            enterCostPrice = "लागत मूल्य (₹)",
            enterSellingPrice = "बिक्री मूल्य (₹ MRP)",
            enterHsn = "HSN कोड",
            enterNotes = "चालान / बिल संदर्भ",
            stockAuditHistory = "लेन-देन ऑडिट इतिहास",
            deleteConfirmTitle = "क्या आप हटाना चाहते हैं?",
            deleteConfirmMessage = "यह उत्पाद और इसके सभी रिकॉर्ड हमेशा के लिए मिटा दिए जाएंगे।",
            confirmDelete = "उत्पाद हटाएं",
            language = "भाषा (Language)",
            changeLanguage = "भाषा बदलें"
        )

        private val Bengali = AppStrings(
            appTitle = "অটোস্টক",
            appSubtitle = "PRO",
            navInventory = "ইনভেন্টরি",
            navScanner = "স্ক্যানার",
            navAlerts = "অ্যালার্ট",
            navAnalytics = "লেজার",
            catAll = "সব",
            catCars = "গাড়ি",
            catBikes = "বাইক",
            catSpareParts = "স্পেয়ার পার্টস",
            category = "ক্যাটাগরি",
            selectCategory = "ক্যাটাগরি নির্বাচন করুন",
            searchPlaceholder = "নাম, SKU, বারকোড বা ফিটমেন্ট দিয়ে খুঁজুন...",
            totalInventoryValue = "মোট মূল্য",
            totalValuation = "মোট স্টক মূল্য",
            totalUnits = "মোট ইউনিট",
            totalItems = "মোট আইটেম",
            totalSkus = "মোট SKU",
            activeAlerts = "অ্যালার্ট",
            addItem = "নতুন যোগ করুন",
            exportPdf = "PDF রিপোর্ট",
            scanCode = "স্ক্যান",
            sortBy = "ক্রমানুসারে সাজান",
            sortNameAsc = "নাম (অ থেকে ক্ষ)",
            sortNameDesc = "নাম (ক্ষ থেকে অ)",
            sortQtyHigh = "স্টক (বেশি থেকে কম)",
            sortQtyLow = "স্টক (কম থেকে বেশি)",
            sortPriceHigh = "দাম (বেশি থেকে কম)",
            sortPriceLow = "দাম (কম থেকে বেশি)",
            sortValuation = "মূল্যায়ন (সর্বোচ্চ)",
            inStock = "মজুদ আছে",
            lowStock = "কম স্টক",
            outOfStock = "স্টক শেষ",
            quickStockIn = "স্টক ইন (+১)",
            quickStockOut = "স্টক আউট (-১)",
            viewDetails = "বিস্তারিত",
            editItem = "সম্পাদনা",
            deleteItem = "মুছে ফেলুন",
            noItemsFound = "কোনো আইটেম পাওয়া যায়নি",
            tryAdjustingFilters = "অনুগ্রহ করে ক্যাটাগরি পরিবর্তন করুন বা সার্চ ক্লিয়ার করুন।",
            sku = "SKU কোড",
            location = "রেক / স্থান",
            unitPrice = "একক মূল্য",
            costPrice = "ক্রয় মূল্য",
            sellingPrice = "বিক্রয় মূল্য (MRP)",
            stockQuantity = "বর্তমান স্টক",
            threshold = "সর্বনিম্ন সীমা",
            hsnCode = "HSN কোড",
            gstRate = "GST হার",
            fitment = "গাড়ির মডেল (Fitment)",
            subcategory = "সাব-ক্যাটাগরি",
            description = "বিবরণ",
            notes = "নোট / চালান #",
            scanTitle = "বারকোড স্ক্যানার",
            scanSubtitle = "EAN-13, QR বা কোড-১২৮ বারকোডে ক্যামেরা রাখুন",
            scannerTitle = "বারকোড স্ক্যানার",
            scannerSubtitle = "দ্রুত যাচাই ও স্টক আপডেট",
            modeLookup = "যাচাই (Lookup)",
            modeStockIn = "স্টক ইন (+১)",
            modeStockOut = "স্টক আউট (-১)",
            alignBarcodePrompt = "বারকোডটি বক্সের মাঝে রাখুন",
            enterBarcodeManually = "ম্যানুয়ালি কোড দিন",
            manualCodeEntry = "ম্যানুয়াল কোড এন্ট্রি",
            quickTestBarcodes = "দ্রুত টেস্ট বারকোড",
            unregisteredBarcode = "অনিবন্ধিত বারকোড",
            unregisteredBarcodeDesc = "এই বারকোডটি ইনভেন্টরি ডাটাবেসে পাওয়া যায়নি।",
            registerProduct = "পণ্য রেজিস্টার করুন",
            registerNewItem = "নতুন পণ্য রেজিস্টার করুন",
            grantPermission = "ক্যামেরা চালু করুন",
            lookupSuccess = "আইটেম পাওয়া গেছে",
            stockInSuccess = "স্টক ইন সফল হয়েছে",
            stockOutSuccess = "স্টক আউট সফল হয়েছে",
            stockOutWarningLow = "স্টক সর্বনিম্ন সীমার নিচে নেমে গেছে",
            outOfStockCannotDeduct = "স্টক খালি, কাটছাঁট করা সম্ভব নয়",
            flashlightOn = "টর্চ অন",
            flashlightOff = "টর্চ অফ",
            flipCamera = "ক্যামেরা পরিবর্তন",
            cancel = "বাতিল",
            save = "সংরক্ষণ",
            add = "যোগ করুন",
            search = "খুঁজুন",
            barcodeTag = "পণ্য বারকোড ট্যাগ",
            recentScansTitle = "সাম্প্রতিক স্ক্যান",
            recentScansSubtitle = "দ্রুত রেফারেন্সের জন্য শেষ ১০টি স্ক্যান করা বারকোড",
            noRecentScans = "এখনো কোনো সাম্প্রতিক স্ক্যান নিবন্ধিত হয়নি",
            clearHistory = "হিস্ট্রি ক্লিয়ার করুন",
            copyBarcode = "কোড কপি করুন",
            barcodeCopied = "বারকোড ক্লিপবোর্ডে কপি করা হয়েছে",
            alertsTitle = "স্টক ওয়াচডগ",
            alertsSubtitle = "জরুরি পুনরায় অর্ডার করার আইটেম",
            allAlerts = "সব অ্যালার্ট",
            criticalZero = "স্টক খালি (0)",
            lowStockFilter = "কম স্টক",
            reorderRecommended = "পুনরায় অর্ডার প্রয়োজন",
            reorderRequired = "জরুরি পুনরায় অর্ডার প্রয়োজন",
            quickRestock = "দ্রুত স্টক ইন",
            stockHealthy = "স্টক অবস্থা ভালো",
            stockHealthyDesc = "সব পণ্য নিরাপদ সীমার উপরে আছে।",
            noAlertsDesc = "কোনো কম স্টক বা খালি আইটেম নেই।",
            analyticsTitle = "স্টক লেজার ও বিবরণী",
            analyticsSubtitle = "মূল্যায়ন, লাভ ও অডিট ইতিহাস",
            totalCostValue = "ক্রয় মূল্যায়ন",
            totalRetailValue = "বিক্রয় মূল্যায়ন",
            projectedProfit = "আনুমানিক লাভ",
            profitMargin = "লাভের শতাংশ",
            marginProfit = "মোট প্রফিট মার্জিন",
            departmentBreakdown = "বিভাগীয় বিবরণ",
            recentStockLedger = "সাম্প্রতিক স্টক রেজিস্টার",
            auditHistory = "স্টক অডিট ইতিহাস",
            noTransactions = "এখনো কোনো লেনদেন নিবন্ধিত হয়নি।",
            pdfExportTitle = "ইনভেন্টরি PDF রিপোর্ট",
            pdfExportSubtitle = "GST বিবরণসহ প্রিন্টযোগ্য PDF তৈরি করুন",
            exportPdfTitle = "ইনভেন্টরি PDF রিপোর্ট তৈরি করুন",
            exportPdfSubtitle = "মূল্য ও GST সহ প্রিন্টযোগ্য রিপোর্ট",
            reportScope = "রিপোর্টের পরিধি",
            requiredStockUnits = "প্রয়োজনীয় স্টক (থ্রেশহোল্ড পূরণ)",
            requiredStockValuation = "প্রয়োজনীয় স্টক মান",
            thresholdUnits = "ন্যূনতম থ্রেশহোল্ড",
            sharePdf = "PDF শেয়ার করুন",
            printPdf = "PDF প্রিন্ট করুন",
            previewPdf = "রিপোর্ট দেখুন",
            generatingPdf = "PDF রিপোর্ট তৈরি হচ্ছে...",
            pdfGenerating = "PDF রিপোর্ট তৈরি হচ্ছে...",
            addNewProduct = "নতুন পণ্য যোগ করুন",
            editProduct = "পণ্য তথ্য পরিবর্তন",
            productDetails = "পণ্যের বিবরণ",
            enterName = "পণ্য / পার্টসের নাম",
            enterSku = "SKU কোড",
            enterBarcode = "বারকোড / EAN-13",
            enterSubcategory = "সাব-ক্যাটাগরি (যেমন: ব্রেকিং, টায়ার)",
            enterFitment = "গাড়ির মডেল (যেমন: সুইফট, সিটি)",
            enterLocation = "রেক/স্থান (যেমন: R-01-A)",
            enterQty = "প্রাথমিক স্টক",
            enterThreshold = "সর্বনিম্ন সীমা",
            enterCostPrice = "ক্রয় মূল্য (₹)",
            enterSellingPrice = "বিক্রয় মূল্য (₹ MRP)",
            enterHsn = "HSN কোড",
            enterNotes = "চালান / বিল রেফারেন্স",
            stockAuditHistory = "লেনদেন অডিট ইতিহাস",
            deleteConfirmTitle = "মুছে ফেলতে চান?",
            deleteConfirmMessage = "এই পণ্য এবং এর সমস্ত লেনদেনের ইতিহাস স্থায়ীভাবে মুছে ফেলা হবে।",
            confirmDelete = "পণ্য মুছে ফেলুন",
            language = "ভাষা (Language)",
            changeLanguage = "ভাষা পরিবর্তন"
        )

        fun getStrings(language: AppLanguage): AppStrings {
            return when (language) {
                AppLanguage.ENGLISH -> English
                AppLanguage.HINDI -> Hindi
                AppLanguage.BENGALI -> Bengali
            }
        }
    }
}

val LocalAppStrings = compositionLocalOf { AppStrings.getStrings(AppLanguage.ENGLISH) }

@Composable
fun currentStrings(): AppStrings = LocalAppStrings.current
